# .github/workflows/tests.yml
# Based on https://github.com/orgs/community/discussions/52616
name: Tests
on:
  # workflow_call is a required field of the "on" property,
  # when intending to use the workflow as a reusable workflow
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Store your packages in .github/apt-packages.txt
      - name: Load package list
        id: package_list
        run: echo "PACKAGES=$(tr '\n' ' ' < .github/apt-packages.txt)" >> $GITHUB_ENV

      # https://github.com/actions/toolkit/issues/946
      - name: Give tar suid root
        run: sudo chown root /bin/tar && sudo chmod u+s /bin/tar
        
      - name: Prepare APT cache dir and symlink
        run: |
          mkdir -p .apt-cache/archives/partial
          sudo rm -rf /var/cache/apt/archives
          sudo ln -s "$PWD/.apt-cache/archives" /var/cache/apt/archives

      - name: Cache APT archive
        id: cache-apt-archive
        uses: actions/cache@v5
        with:
          path: .apt-cache/archives
          key: |
            ${{ runner.os }}-apt-cache-${{ hashFiles('.github/apt-packages.txt') }}
          restore-keys: |
            ${{ runner.os }}-apt-cache-
            
      - name: Prepare APT cache dir and symlink
        if: steps.cache-texlive.outputs.cache-hit != 'true'
        run: |
         sudo apt-get update
         sudo apt-get install -y -d $PACKAGES

      - name: Clean APT Cache locks & fix permissions
        if: always()
        run: |
          sudo rm -f /var/cache/apt/archives/lock
          #sudo rm -f /var/lib/dpkg/lock-frontend || true
          #sudo rm -f /var/lib/apt/lists/lock || true
          sudo chown -R $USER:$USER .apt-cache/archives

      - name: Install TeXLive
        run:
          sudo apt-get install -y $PACKAGES

      - name: Test LaTeX
        run: |
          echo $PATH
          type pdflatex
          pdflatex -v
      # - name: Install Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: ${{ inputs.python_version }}
      #     # architecture: x64
      # - name: Install Nox
      #   run: pipx install nox
      # - name: Run Tests
      #   run: nox -p ${{ inputs.python_version }}
      #   # https://github.com/mamba-org/setup-micromamba
      #   #uses: mamba-org/setup-micromamba@v2
      #   #micromamba-version: '1.4.8-0'
      #   ##environment-file: environment.yml
      #   #init-shell: >-
      #   #  bash
      #   #post-cleanup: 'all'
