# .github/workflows/tests.yml
# Based on https://github.com/orgs/community/discussions/52616
name: Tests
on:
  # workflow_call is a required field of the "on" property,
  # when intending to use the workflow as a reusable workflow
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Needed to allow tar root access when restoring system files
      # See: https://github.com/actions/toolkit/issues/946
      - name: root suid tar
        run: sudo chown root /bin/tar && sudo chmod u+s /bin/tar
        
      - name: Cache TeXLive install
        id: cache-texlive
        uses: actions/cache@v5
        with:
          path: |
            /usr/share/texlive
            #/var/lib/texmf
            /etc/texmf
          key: texlive-cache-2026-Mar-1.2

      - name: Install TeXLive (if not cached)
        if: steps.cache-texlive.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive

      - name: Add TeXLive to PATH (if cached)
        if: steps.cache-texlive.outputs.cache-hit == 'true'
        run: echo
      - name: Test LaTeX
        run: |
          echo $PATH
          type pdflatex
          pdflatex -v
      # - name: Install Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: ${{ inputs.python_version }}
      #     # architecture: x64
      # - name: Install Nox
      #   run: pipx install nox
      # - name: Run Tests
      #   run: nox -p ${{ inputs.python_version }}
      #   # https://github.com/mamba-org/setup-micromamba
      #   #uses: mamba-org/setup-micromamba@v2
      #   #micromamba-version: '1.4.8-0'
      #   ##environment-file: environment.yml
      #   #init-shell: >-
      #   #  bash
      #   #post-cleanup: 'all'
